/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#3cd7ff',
        'primary-container': '#00d4ff',
        'on-secondary-fixed': '#25005a',
        'background': '#0e1322',
        'error': '#ffb4ab',
        'on-background': '#dee1f7',
        'secondary-fixed': '#eaddff',
        'primary-fixed': '#b4ebff',
        'on-tertiary': '#003824',
        'on-tertiary-container': '#005c3e',
        'on-error': '#690005',
        'surface-container-highest': '#2f3445',
        'on-primary': '#003642',
        'on-secondary-fixed-variant': '#5a00c6',
        'surface': '#0e1322',
        'secondary': '#d2bbff',
        'on-secondary-container': '#c9aeff',
        'inverse-on-surface': '#2b3040',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004e5f',
        'tertiary-container': '#49da9f',
        'tertiary': '#6af7ba',
        'surface-container': '#1a1f2f',
        'on-primary-container': '#00586b',
        'surface-tint': '#3cd7ff',
        'surface-variant': '#2f3445',
        'secondary-container': '#6001d1',
        'tertiary-fixed-dim': '#4edea3',
        'inverse-surface': '#dee1f7',
        'inverse-primary': '#00677e',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary-fixed': '#002113',
        'on-surface': '#dee1f7',
        'on-tertiary-fixed-variant': '#005236',
        'secondary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#001f27',
        'on-secondary': '#3f008e',
        'surface-dim': '#0e1322',
        'surface-container-lowest': '#090e1c',
        'surface-bright': '#343949',
        'primary': '#a8e8ff',
        'outline': '#859398',
        'surface-container-low': '#161b2b',
        'surface-container-high': '#25293a',
        'on-surface-variant': '#bbc9cf',
        'error-container': '#93000a',
        'outline-variant': '#3c494e',
        'amber': '#f59e0b',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'monospace'],
        body: ['Space Grotesk', 'monospace'],
        label: ['Space Grotesk', 'monospace'],
      },
    },
  },
  plugins: [],
}
